In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
df = pd.read_csv("cleaned_croma_laptops.csv")

In [55]:
df.head()

,Brand,Screen Size,Color,RAM,Storage,GPU,CPU,Price
0,Apple,13.3,Gray,8,256.0,Integrated,Intel Core i5 13th,54490.0
1,Apple,13.3,Gold,8,256.0,Integrated,Intel Core i5 13th,54490.0
2,Apple,13.3,Silver,8,256.0,Integrated,Intel Core i5 13th,54490.0
3,Apple,14.2,Black,24,512.0,Integrated,Intel Core i5 13th,187990.0
4,Apple,13.6,Silver,16,256.0,Integrated,Intel Core i5 13th,93990.0

In [41]:
df.head()

,Brand,Screen Size,Color,RAM,Storage,GPU,CPU,Price
0,Apple,13.3,Gray,8,256.0,Integrated,Intel Core i5 13th,54490.0
1,Apple,13.3,Gold,8,256.0,Integrated,Intel Core i5 13th,54490.0
2,Apple,13.3,Silver,8,256.0,Integrated,Intel Core i5 13th,54490.0
3,Apple,14.2,Black,24,512.0,Integrated,Intel Core i5 13th,187990.0
4,Apple,13.6,Silver,16,256.0,Integrated,Intel Core i5 13th,93990.0

In [42]:
X = df.drop("Price", axis=1)
y = df["Price"]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 473 entries, 0 to 472
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Brand        473 non-null    object
 1   Screen Size  473 non-null    float64
 2   Color        473 non-null    object
 3   RAM          473 non-null    int64
 4   Storage      473 non-null    float64
 5   GPU          473 non-null    object
 6   CPU          473 non-null    object
 7   Price        473 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 29.7+ KB

In [44]:
categorical_features = X.select_dtypes(include=["object"]).columns
numeric_features = X.select_dtypes(include=[np.number]).columns

In [45]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [46]:
model = Pipeline(steps=[("preprocessor", preprocessor), ("regressor", LinearRegression())])

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Screen Size', 'RAM', 'Storage'], dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['Brand', 'Color', 'GPU', 'CPU'], dtype='object'))])),
                ('regressor', LinearRegression())])

In [49]:
y_pred = model.predict(X_test)

In [50]:
y_pred

array([ 63834.26721898,  74542.7083945 ,  43156.63744348, 139230.96977147,
        65541.99176067, 100741.03815372,  80235.30175609, 120553.26188075,
        64380.82535533, 109416.5703883 ,  59667.88526567,  51028.69096588,
        75539.87833243,  44036.28254816, 175629.43802493,  26628.08027507,
        89607.61127454, 170978.76156141,  49906.58745727,  41896.91167227,
        76727.88599479, 204955.31466157,  97367.64659896,  80751.96644904,
        70952.29666052,  86362.75541623,  83728.67087752,  66693.35649333,
        76682.07927038, 101485.5623885 ,  72526.59750774,  82140.16575202,
        75848.41246213, 214023.47496667,  34245.40667163,  75402.85960451,
        62759.2663954 , 107163.40755652,  27102.80202542, 272179.65682828,
       133052.61823115,  43411.68809019, 146760.32100502, 212780.09586802,
       214023.47496667, 139573.66433249,  95380.7474155 ,  49361.46456421,
        48365.34257119,  46117.71480288, 163031.38479154,  75715.36926221,
       112712.63934463, 132667.04934832,  76682.07927038,  82140.16575202,
       102712.59867093,  24470.48667189,  84034.89078022,  29862.14311241,
       115281.88262563,  71527.14780141, 124134.18771382, 106314.19687888,
       125198.54281594, 259693.75335697,  62182.69229779, 101469.21957229,
        11479.00807021, 101469.21957229, 275129.06906032,  49155.80544518,
        72526.59750774,  56163.84473434,  81260.69221936,  75402.85960451,
         4550.02666739, 130013.44332118,  46869.45181025,  34871.44044461,
        89406.49424684, 171573.02233157, 226160.37397699,  76682.07927038,
        69409.39430036,  30544.12446297,  93090.13859788, 126745.06630016,
        79725.818101  , 105382.92307165,  69409.39430036, 118279.46099745,
        35936.96897422,  87259.53708901,  62182.69229779])

In [51]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [52]:
print("Model Performance (Linear Regression)")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

Model Performance (Linear Regression)
MAE : 25356.396493791548
RMSE: 34052.640634574556
R²  : 0.7280273221087303

In [53]:
import pickle

In [54]:
with open("linear_laptop_price_model.pkl", "wb") as f:
    pickle.dump(linreg_model, f)